# Generated by Django 5.1.1 on 2024-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='name',
        ),
        migrations.AddField(
            model_name='rule',
            name='ast',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
